name: Daily PBF fetch

on:
  schedule:
    - cron: '30 7 * * *'
  push:
    tags:
      - test.fetch*

jobs:
  fetch-pbf:
    runs-on: ubuntu-latest
    env:
      DAILY_PBF: taiwan-daily.osm.pbf
      DAILY_PBF_MD5: taiwan-daily.osm.pbf.md5
      github_api_token: ${{ secrets.GITHUB_TOKEN }}
      repo: ${{ github.repository }}
      tag: daily-taiwan-pbf

    steps:
      #- name: Download latest osm.pbf from geofabrik
      #  run: curl -o $DAILY_PBF http://download.geofabrik.de/asia/taiwan-latest.osm.pbf
      - name: Checkout master branch
        uses: actions/checkout@v2
      - name: Download latest osm.pbf from Protomaps
        run: scripts/protomaps_extracts.sh
        env:
          PROTOMAPS_TOKEN: ${{ secrets.PROTOMAPS_TOKEN }}
          OUTPUT: ${{ env.DAILY_PBF }}

      - name: Upload PBF file to Release Asset
        uses: typebrook/github-release@v5
        env:
          type: asset
          filename: ${{ env.DAILY_PBF }}
          action: overwrite

      - run: echo $(md5sum $DAILY_PBF) > $DAILY_PBF_MD5
      - name: Upload MD5 to Release Asset
        uses: typebrook/github-release@v5
        env:
          type: asset
          filename: ${{ env.DAILY_PBF_MD5 }}
          action: overwrite

      - name: Make release note
        run: |
          echo "## $DAILY_PBF" > note
          echo 'Daily OSM PBF file with extent of Taiwan, comes from Geofabrik.' >> note
          echo "Contains OSM data up to $(osmconvert $DAILY_PBF --out-timestamp)." >> note
          echo >> note
          echo "**md5:** $(cat $DAILY_PBF_MD5 | cut -d ' ' -f1)" >> note
          echo "**source:** http://download.geofabrik.de/asia/taiwan.html" >> note
      - name: Update release note
        uses: typebrook/github-release@v5
        env:
          type: edit
          filename: note
